source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LKUserDefaultOption_Example', :exclusive => true do
  pod "LKUserDefaultOption", :path => "../"
end

target 'LKUserDefaultOption_Tests', :exclusive => true do
  pod "LKUserDefaultOption", :path => "../"

  
end
